using NeonTrader.Models;
using Newtonsoft.Json.Linq;
using Xunit;

namespace NeonTrader.Tests.Models;

[Collection("Sequential")]
public class ShipTests
{
    private Ship CreateValidShip(string id = "ship_test", string name = "Test Ship")
    {
        return new Ship
        {
            Id = id, Name = name, ShipClassId = "sc_fighter", CurrentHull = 200, MaxHull = 200,
            CurrentShield = 100, MaxShield = 100, ShieldRechargeRate = 10, CargoCapacity = 100,
            FuelCapacity = 200, CurrentFuel = 200, FuelConsumption = 1.5, MaxSpeed = 300,
            Acceleration = 80, TurnRate = 120, WeaponHardpoints = 3, UtilityHardpoints = 2,
            UpgradeSlots = 4, Condition = 1.0, TotalDistanceTraveled = 500, TotalCreditsEarned = 100000,
            HomePort = "Neon Station", PurchaseDate = new DateTime(2087, 1, 15)
        };
    }

    // Validation
    [Fact] public void Validate_ValidShip_ReturnsTrue() { var s = CreateValidShip(); Assert.True(s.Validate(out var e)); Assert.Empty(e); }
    [Fact] public void Validate_EmptyId_ReturnsFalse() { var s = CreateValidShip(); s.Id = ""; Assert.False(s.Validate(out var e)); Assert.Contains("ID", e); }
    [Fact] public void Validate_WhitespaceId_ReturnsFalse() { var s = CreateValidShip(); s.Id = "   "; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_EmptyShipClassId_ReturnsFalse() { var s = CreateValidShip(); s.ShipClassId = ""; Assert.False(s.Validate(out var e)); Assert.Contains("class", e); }
    [Fact] public void Validate_CurrentHullNegative_ReturnsFalse() { var s = CreateValidShip(); s.CurrentHull = -1; Assert.False(s.Validate(out var e)); Assert.Contains("hull", e); }
    [Fact] public void Validate_CurrentHullExceedsMax_ReturnsFalse() { var s = CreateValidShip(); s.MaxHull = 200; s.CurrentHull = 250; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_MaxHullZero_ReturnsFalse() { var s = CreateValidShip(); s.MaxHull = 0; Assert.False(s.Validate(out var e)); Assert.Contains("hull", e.ToLower()); }
    [Fact] public void Validate_MaxHullNegative_ReturnsFalse() { var s = CreateValidShip(); s.MaxHull = -10; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_CurrentShieldNegative_ReturnsFalse() { var s = CreateValidShip(); s.CurrentShield = -1; Assert.False(s.Validate(out var e)); Assert.Contains("shield", e); }
    [Fact] public void Validate_CurrentShieldExceedsMax_ReturnsFalse() { var s = CreateValidShip(); s.MaxShield = 100; s.CurrentShield = 150; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_MaxShieldNegative_ReturnsFalse() { var s = CreateValidShip(); s.MaxShield = -1; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_NegativeCargoCapacity_ReturnsFalse() { var s = CreateValidShip(); s.CargoCapacity = -1; Assert.False(s.Validate(out var e)); Assert.Contains("Cargo", e); }
    [Fact] public void Validate_ZeroFuelCapacity_ReturnsFalse() { var s = CreateValidShip(); s.FuelCapacity = 0; Assert.False(s.Validate(out var e)); Assert.Contains("Fuel capacity", e); }
    [Fact] public void Validate_CurrentFuelNegative_ReturnsFalse() { var s = CreateValidShip(); s.CurrentFuel = -1; Assert.False(s.Validate(out var e)); Assert.Contains("fuel", e); }
    [Fact] public void Validate_CurrentFuelExceedsCapacity_ReturnsFalse() { var s = CreateValidShip(); s.FuelCapacity = 200; s.CurrentFuel = 250; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_ZeroFuelConsumption_ReturnsFalse() { var s = CreateValidShip(); s.FuelConsumption = 0; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_NegativeFuelConsumption_ReturnsFalse() { var s = CreateValidShip(); s.FuelConsumption = -1; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_ConditionOutOfRange_ReturnsFalse() { var s = CreateValidShip(); s.Condition = 1.5; Assert.False(s.Validate(out var e)); Assert.Contains("Condition", e); }
    [Fact] public void Validate_ConditionNegative_ReturnsFalse() { var s = CreateValidShip(); s.Condition = -0.1; Assert.False(s.Validate(out var e)); }
    [Fact] public void Validate_ZeroShield_Valid() { var s = CreateValidShip(); s.MaxShield = 0; s.CurrentShield = 0; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_ZeroCargoCapacity_Valid() { var s = CreateValidShip(); s.CargoCapacity = 0; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_ConditionZero_Valid() { var s = CreateValidShip(); s.Condition = 0; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_ConditionOne_Valid() { var s = CreateValidShip(); s.Condition = 1.0; Assert.True(s.Validate(out _)); }

    // Damage Pipeline
    [Fact] public void TakeDamage_ShieldsAbsorbFirst() { var s = CreateValidShip(); s.CurrentShield = 100; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(50); Assert.Equal(50, s.CurrentShield); Assert.Equal(200, s.CurrentHull); Assert.Equal(1.0, s.Condition); }
    [Fact] public void TakeDamage_ShieldsPartiallyAbsorb() { var s = CreateValidShip(); s.CurrentShield = 30; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(100); Assert.Equal(0, s.CurrentShield); Assert.Equal(130, s.CurrentHull); Assert.True(Math.Abs(0.3 - s.Condition) < 0.0001); }
    [Fact] public void TakeDamage_NoShields_AllToHull() { var s = CreateValidShip(); s.CurrentShield = 0; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(50); Assert.Equal(0, s.CurrentShield); Assert.Equal(150, s.CurrentHull); Assert.Equal(0.5, s.Condition); }
    [Fact] public void TakeDamage_Overkill_HullClampedToZero() { var s = CreateValidShip(); s.CurrentShield = 0; s.CurrentHull = 50; s.Condition = 0.5; s.TakeDamage(200); Assert.Equal(0, s.CurrentHull); Assert.Equal(0, s.Condition); Assert.True(s.IsDestroyed); }
    [Fact] public void TakeDamage_ExactKill() { var s = CreateValidShip(); s.CurrentShield = 0; s.CurrentHull = 100; s.Condition = 1.0; s.TakeDamage(100); Assert.Equal(0, s.CurrentHull); Assert.Equal(0, s.Condition); Assert.True(s.IsDestroyed); }
    [Fact] public void TakeDamage_ShieldsExactDepletion() { var s = CreateValidShip(); s.CurrentShield = 50; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(50); Assert.Equal(0, s.CurrentShield); Assert.Equal(200, s.CurrentHull); Assert.Equal(1.0, s.Condition); }
    [Fact] public void TakeDamage_ZeroDamage_NoEffect() { var s = CreateValidShip(); s.CurrentShield = 100; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(0); Assert.Equal(100, s.CurrentShield); Assert.Equal(200, s.CurrentHull); Assert.Equal(1.0, s.Condition); }
    [Fact] public void TakeDamage_MultipleHits_ConditionDegrades() { var s = CreateValidShip(); s.CurrentShield = 0; s.CurrentHull = 200; s.Condition = 1.0; s.TakeDamage(30); Assert.True(Math.Abs(0.7 - s.Condition) < 0.0001); s.TakeDamage(30); Assert.True(Math.Abs(0.4 - s.Condition) < 0.0001); s.TakeDamage(30); Assert.True(Math.Abs(0.1 - s.Condition) < 0.0001); }

    // Repair
    [Fact] public void RepairHull_RepairsDamage() { var s = CreateValidShip(); s.CurrentHull = 150; s.MaxHull = 200; s.Condition = 0.5; var r = s.RepairHull(30); Assert.Equal(30, r); Assert.Equal(180, s.CurrentHull); Assert.Equal(0.65, s.Condition); }
    [Fact] public void RepairHull_CappedAtMax() { var s = CreateValidShip(); s.CurrentHull = 190; s.MaxHull = 200; var r = s.RepairHull(50); Assert.Equal(10, r); Assert.Equal(200, s.CurrentHull); }
    [Fact] public void RepairHull_AlreadyFull_ReturnsZero() { var s = CreateValidShip(); s.CurrentHull = 200; s.MaxHull = 200; Assert.Equal(0, s.RepairHull(50)); Assert.Equal(200, s.CurrentHull); }
    [Fact] public void RepairHull_ConditionCappedAtOne() { var s = CreateValidShip(); s.CurrentHull = 100; s.MaxHull = 200; s.Condition = 0.95; s.RepairHull(50); Assert.Equal(1.0, s.Condition); }
    [Fact] public void RepairHull_ZeroRepair_NoEffect() { var s = CreateValidShip(); s.CurrentHull = 150; s.MaxHull = 200; s.Condition = 0.5; Assert.Equal(0, s.RepairHull(0)); Assert.Equal(150, s.CurrentHull); Assert.Equal(0.5, s.Condition); }

    // Shield Recharge
    [Fact] public void RechargeShields_RechargesOverTime() { var s = CreateValidShip(); s.CurrentShield = 50; s.MaxShield = 100; s.ShieldRechargeRate = 10; s.RechargeShields(2.0); Assert.Equal(70, s.CurrentShield); }
    [Fact] public void RechargeShields_CappedAtMax() { var s = CreateValidShip(); s.CurrentShield = 95; s.MaxShield = 100; s.ShieldRechargeRate = 10; s.RechargeShields(2.0); Assert.Equal(100, s.CurrentShield); }
    [Fact] public void RechargeShields_NoShieldCapacity_NoRecharge() { var s = CreateValidShip(); s.CurrentShield = 0; s.MaxShield = 0; s.ShieldRechargeRate = 10; s.RechargeShields(5.0); Assert.Equal(0, s.CurrentShield); }
    [Fact] public void RechargeShields_AlreadyFull_NoChange() { var s = CreateValidShip(); s.CurrentShield = 100; s.MaxShield = 100; s.ShieldRechargeRate = 10; s.RechargeShields(5.0); Assert.Equal(100, s.CurrentShield); }
    [Fact] public void RechargeShields_ZeroRechargeRate_NoRecharge() { var s = CreateValidShip(); s.CurrentShield = 50; s.MaxShield = 100; s.ShieldRechargeRate = 0; s.RechargeShields(5.0); Assert.Equal(50, s.CurrentShield); }
    [Fact] public void RechargeShields_ZeroDeltaTime_NoRecharge() { var s = CreateValidShip(); s.CurrentShield = 50; s.MaxShield = 100; s.ShieldRechargeRate = 10; s.RechargeShields(0); Assert.Equal(50, s.CurrentShield); }

    // Fuel
    [Fact] public void ConsumeFuel_SufficientFuel_ReturnsTrue() { var s = CreateValidShip(); s.CurrentFuel = 200; Assert.True(s.ConsumeFuel(50)); Assert.Equal(150, s.CurrentFuel); }
    [Fact] public void ConsumeFuel_InsufficientFuel_ReturnsFalse() { var s = CreateValidShip(); s.CurrentFuel = 30; Assert.False(s.ConsumeFuel(50)); Assert.Equal(30, s.CurrentFuel); }
    [Fact] public void ConsumeFuel_ExactAmount_ReturnsTrue() { var s = CreateValidShip(); s.CurrentFuel = 50; Assert.True(s.ConsumeFuel(50)); Assert.Equal(0, s.CurrentFuel); }
    [Fact] public void ConsumeFuel_ZeroAmount_ReturnsTrue() { var s = CreateValidShip(); s.CurrentFuel = 100; Assert.True(s.ConsumeFuel(0)); Assert.Equal(100, s.CurrentFuel); }
    [Fact] public void Refuel_PartialFill_ReturnsActualAmount() { var s = CreateValidShip(); s.CurrentFuel = 100; s.FuelCapacity = 200; Assert.Equal(50, s.Refuel(50)); Assert.Equal(150, s.CurrentFuel); }
    [Fact] public void Refuel_Overfill_CappedAtCapacity() { var s = CreateValidShip(); s.CurrentFuel = 180; s.FuelCapacity = 200; Assert.Equal(20, s.Refuel(100)); Assert.Equal(200, s.CurrentFuel); }
    [Fact] public void Refuel_AlreadyFull_ReturnsZero() { var s = CreateValidShip(); s.CurrentFuel = 200; s.FuelCapacity = 200; Assert.Equal(0, s.Refuel(50)); Assert.Equal(200, s.CurrentFuel); }
    [Fact] public void Refuel_ZeroAmount_ReturnsZero() { var s = CreateValidShip(); s.CurrentFuel = 100; s.FuelCapacity = 200; Assert.Equal(0, s.Refuel(0)); Assert.Equal(100, s.CurrentFuel); }

    // Cargo
    [Fact] public void GetCargoUsed_EmptyCargo_ReturnsZero() { var s = CreateValidShip(); Assert.Equal(0, s.GetCargoUsed()); }
    [Fact] public void GetCargoUsed_WithCargo_ReturnsSum() { var s = CreateValidShip(); s.Cargo["water"] = 10; s.Cargo["food"] = 5; s.Cargo["ore"] = 20; Assert.Equal(35, s.GetCargoUsed()); }
    [Fact] public void GetAvailableCargoSpace_CalculatesCorrectly() { var s = CreateValidShip(); s.CargoCapacity = 100; s.Cargo["water"] = 30; Assert.Equal(70, s.GetAvailableCargoSpace()); }
    [Fact] public void HasCargoSpace_SufficientSpace_ReturnsTrue() { var s = CreateValidShip(); s.CargoCapacity = 100; Assert.True(s.HasCargoSpace(50)); }
    [Fact] public void HasCargoSpace_InsufficientSpace_ReturnsFalse() { var s = CreateValidShip(); s.CargoCapacity = 100; s.Cargo["ore"] = 80; Assert.False(s.HasCargoSpace(30)); }
    [Fact] public void HasCargoSpace_ExactSpace_ReturnsTrue() { var s = CreateValidShip(); s.CargoCapacity = 100; s.Cargo["ore"] = 50; Assert.True(s.HasCargoSpace(50)); }
    [Fact] public void AddCargo_NewCommodity_ReturnsTrue() { var s = CreateValidShip(); s.CargoCapacity = 100; Assert.True(s.AddCargo("water", 20)); Assert.Equal(20, s.Cargo["water"]); }
    [Fact] public void AddCargo_ExistingCommodity_StacksQuantity() { var s = CreateValidShip(); s.CargoCapacity = 100; s.Cargo["water"] = 15; Assert.True(s.AddCargo("water", 10)); Assert.Equal(25, s.Cargo["water"]); }
    [Fact] public void AddCargo_InsufficientSpace_ReturnsFalse() { var s = CreateValidShip(); s.CargoCapacity = 50; s.Cargo["ore"] = 40; Assert.False(s.AddCargo("water", 20)); Assert.False(s.Cargo.ContainsKey("water")); }
    [Fact] public void AddCargo_ZeroQuantity_ReturnsTrue() { var s = CreateValidShip(); s.CargoCapacity = 100; Assert.True(s.AddCargo("water", 0)); Assert.Equal(0, s.GetCargoQuantity("water")); }
    [Fact] public void RemoveCargo_SufficientQuantity_ReturnsTrue() { var s = CreateValidShip(); s.Cargo["water"] = 30; Assert.True(s.RemoveCargo("water", 10)); Assert.Equal(20, s.Cargo["water"]); }
    [Fact] public void RemoveCargo_ExactQuantity_RemovesEntry() { var s = CreateValidShip(); s.Cargo["water"] = 10; Assert.True(s.RemoveCargo("water", 10)); Assert.False(s.Cargo.ContainsKey("water")); }
    [Fact] public void RemoveCargo_MoreThanAvailable_ReturnsFalse() { var s = CreateValidShip(); s.Cargo["water"] = 5; Assert.False(s.RemoveCargo("water", 10)); Assert.Equal(5, s.Cargo["water"]); }
    [Fact] public void RemoveCargo_NonexistentCommodity_ReturnsFalse() { var s = CreateValidShip(); Assert.False(s.RemoveCargo("nonexistent", 10)); }
    [Fact] public void GetCargoQuantity_Existing_ReturnsQuantity() { var s = CreateValidShip(); s.Cargo["water"] = 25; Assert.Equal(25, s.GetCargoQuantity("water")); }
    [Fact] public void GetCargoQuantity_Nonexistent_ReturnsZero() { var s = CreateValidShip(); Assert.Equal(0, s.GetCargoQuantity("nonexistent")); }
    [Fact] public void Cargo_AddRemoveSequence() { var s = CreateValidShip(); s.CargoCapacity = 200; Assert.True(s.AddCargo("water", 50)); Assert.True(s.AddCargo("food", 30)); Assert.True(s.AddCargo("water", 20)); Assert.Equal(70, s.GetCargoQuantity("water")); Assert.Equal(30, s.GetCargoQuantity("food")); Assert.Equal(100, s.GetCargoUsed()); Assert.True(s.RemoveCargo("water", 40)); Assert.Equal(30, s.GetCargoQuantity("water")); Assert.Equal(60, s.GetCargoUsed()); Assert.True(s.RemoveCargo("food", 30)); Assert.False(s.Cargo.ContainsKey("food")); Assert.Equal(30, s.GetCargoUsed()); }

    // Equipment Install/Remove
    [Fact] public void InstallEquipment_EmptySlot_ReturnsTrue() { var s = CreateValidShip(); Assert.True(s.InstallEquipment("slot_engine", "eq_engine_1")); Assert.True(s.HasEquipmentInSlot("slot_engine")); Assert.Equal("eq_engine_1", s.GetEquipmentInSlot("slot_engine")); }
    [Fact] public void InstallEquipment_OccupiedSlot_ReturnsFalse() { var s = CreateValidShip(); s.InstallEquipment("slot_engine", "eq_engine_1"); Assert.False(s.InstallEquipment("slot_engine", "eq_engine_2")); Assert.Equal("eq_engine_1", s.GetEquipmentInSlot("slot_engine")); }
    [Fact] public void RemoveEquipment_InstalledEquipment_ReturnsTrue() { var s = CreateValidShip(); s.InstallEquipment("slot_engine", "eq_engine_1"); Assert.True(s.RemoveEquipment("slot_engine", out var id)); Assert.Equal("eq_engine_1", id); Assert.False(s.HasEquipmentInSlot("slot_engine")); }
    [Fact] public void RemoveEquipment_EmptySlot_ReturnsFalse() { var s = CreateValidShip(); Assert.False(s.RemoveEquipment("slot_engine", out var id)); Assert.Equal(string.Empty, id); }
    [Fact] public void HasEquipmentInSlot_Installed_ReturnsTrue() { var s = CreateValidShip(); s.InstallEquipment("slot_weapon_1", "wpn_laser"); Assert.True(s.HasEquipmentInSlot("slot_weapon_1")); }
    [Fact] public void HasEquipmentInSlot_Empty_ReturnsFalse() { var s = CreateValidShip(); Assert.False(s.HasEquipmentInSlot("slot_weapon_1")); }
    [Fact] public void GetEquipmentInSlot_Installed_ReturnsId() { var s = CreateValidShip(); s.InstallEquipment("slot_shield", "shld_gen"); Assert.Equal("shld_gen", s.GetEquipmentInSlot("slot_shield")); }
    [Fact] public void GetEquipmentInSlot_Empty_ReturnsNull() { var s = CreateValidShip(); Assert.Null(s.GetEquipmentInSlot("slot_shield")); }
    [Fact] public void Equipment_MultipleSlots_Independent() { var s = CreateValidShip(); s.InstallEquipment("slot_1", "eq_a"); s.InstallEquipment("slot_2", "eq_b"); s.InstallEquipment("slot_3", "eq_c"); Assert.Equal("eq_a", s.GetEquipmentInSlot("slot_1")); Assert.Equal("eq_b", s.GetEquipmentInSlot("slot_2")); Assert.Equal("eq_c", s.GetEquipmentInSlot("slot_3")); s.RemoveEquipment("slot_2", out _); Assert.Null(s.GetEquipmentInSlot("slot_2")); Assert.Equal("eq_a", s.GetEquipmentInSlot("slot_1")); Assert.Equal("eq_c", s.GetEquipmentInSlot("slot_3")); }

    // Hardpoint Tracking
    [Fact] public void GetFreeWeaponHardpoints_NoEquipment_ReturnsAll() { var s = CreateValidShip(); s.WeaponHardpoints = 3; Assert.Equal(3, s.GetFreeWeaponHardpoints()); }
    [Fact] public void GetFreeWeaponHardpoints_WithWeapons_ReturnsRemaining() { EquipmentRegistry.Clear(); var w = new Weapon { Id = "wpn_test", Name = "Test Weapon", Type = EquipmentType.Weapon, Damage = 10, Range = 1000, OptimalRange = 500, FalloffRange = 1500, FireRate = 1.0, ProjectileSpeed = 500, Accuracy = 0.9, CritChance = 0.05, CritMultiplier = 2.0 }; EquipmentRegistry.Register(w); var s = CreateValidShip(); s.WeaponHardpoints = 3; s.InstallEquipment("slot_w1", "wpn_test"); s.InstallEquipment("slot_w2", "wpn_test"); Assert.Equal(1, s.GetFreeWeaponHardpoints()); }
    [Fact] public void GetFreeWeaponHardpoints_NonWeaponEquipment_NotCounted() { EquipmentRegistry.Clear(); var sh = new Shield { Id = "shld_test", Name = "Test Shield", Type = EquipmentType.Shield, Capacity = 100, RechargeRate = 10, RechargeDelay = 3 }; EquipmentRegistry.Register(sh); var s = CreateValidShip(); s.WeaponHardpoints = 3; s.InstallEquipment("slot_s1", "shld_test"); Assert.Equal(3, s.GetFreeWeaponHardpoints()); }
    [Fact] public void GetFreeUtilityHardpoints_NoEquipment_ReturnsAll() { var s = CreateValidShip(); s.UtilityHardpoints = 2; Assert.Equal(2, s.GetFreeUtilityHardpoints()); }
    [Fact] public void GetFreeUtilityHardpoints_WithNonWeaponEquipment_ReturnsRemaining() { EquipmentRegistry.Clear(); var sh = new Shield { Id = "shld_util", Name = "Utility Shield", Type = EquipmentType.Shield, Capacity = 100, RechargeRate = 10, RechargeDelay = 3 }; EquipmentRegistry.Register(sh); var s = CreateValidShip(); s.UtilityHardpoints = 2; s.InstallEquipment("slot_u1", "shld_util"); Assert.Equal(1, s.GetFreeUtilityHardpoints()); }
    [Fact] public void GetFreeUtilityHardpoints_WeaponEquipment_NotCounted() { EquipmentRegistry.Clear(); var w = new Weapon { Id = "wpn_util_test", Name = "Test Weapon", Type = EquipmentType.Weapon, Damage = 10, Range = 1000, OptimalRange = 500, FalloffRange = 1500, FireRate = 1.0, ProjectileSpeed = 500, Accuracy = 0.9, CritChance = 0.05, CritMultiplier = 2.0 }; EquipmentRegistry.Register(w); var s = CreateValidShip(); s.UtilityHardpoints = 2; s.InstallEquipment("slot_w1", "wpn_util_test"); Assert.Equal(2, s.GetFreeUtilityHardpoints()); }
    [Fact] public void GetFreeWeaponHardpoints_UnregisteredEquipment_NotCounted() { EquipmentRegistry.Clear(); var s = CreateValidShip(); s.WeaponHardpoints = 3; s.InstallEquipment("slot_w1", "nonexistent_weapon"); Assert.Equal(3, s.GetFreeWeaponHardpoints()); }

    // IsDestroyed
    [Fact] public void IsDestroyed_ZeroHull_ReturnsTrue() { var s = CreateValidShip(); s.CurrentHull = 0; Assert.True(s.IsDestroyed); }
    [Fact] public void IsDestroyed_PositiveHull_ReturnsFalse() { var s = CreateValidShip(); s.CurrentHull = 1; Assert.False(s.IsDestroyed); }
    [Fact] public void IsDestroyed_NegativeHull_ReturnsTrue() { var s = CreateValidShip(); s.CurrentHull = -5; Assert.True(s.IsDestroyed); }

    // Clone
    [Fact] public void Clone_CreatesDeepCopy() { var s = CreateValidShip(); s.Cargo["water"] = 10; s.Cargo["food"] = 5; s.InstalledEquipment["slot_engine"] = "eq_engine"; s.InstalledEquipment["slot_shield"] = "eq_shield"; s.InstalledUpgrades.Add("upg_armor"); s.InstalledUpgrades.Add("upg_speed"); s.Tags.Add("military"); s.Tags.Add("stealth"); var c = s.Clone(); Assert.Equal(s.Id, c.Id); Assert.Equal(s.Name, c.Name); Assert.Equal(s.ShipClassId, c.ShipClassId); Assert.Equal(s.CurrentHull, c.CurrentHull); Assert.Equal(s.MaxHull, c.MaxHull); Assert.Equal(s.CurrentShield, c.CurrentShield); Assert.Equal(s.MaxShield, c.MaxShield); Assert.Equal(s.ShieldRechargeRate, c.ShieldRechargeRate); Assert.Equal(s.CargoCapacity, c.CargoCapacity); Assert.Equal(s.FuelCapacity, c.FuelCapacity); Assert.Equal(s.CurrentFuel, c.CurrentFuel); Assert.Equal(s.FuelConsumption, c.FuelConsumption); Assert.Equal(s.MaxSpeed, c.MaxSpeed); Assert.Equal(s.Acceleration, c.Acceleration); Assert.Equal(s.TurnRate, c.TurnRate); Assert.Equal(s.WeaponHardpoints, c.WeaponHardpoints); Assert.Equal(s.UtilityHardpoints, c.UtilityHardpoints); Assert.Equal(s.UpgradeSlots, c.UpgradeSlots); Assert.Equal(s.Condition, c.Condition); Assert.Equal(s.TotalDistanceTraveled, c.TotalDistanceTraveled); Assert.Equal(s.TotalCreditsEarned, c.TotalCreditsEarned); Assert.Equal(s.HomePort, c.HomePort); Assert.Equal(s.PurchaseDate, c.PurchaseDate); Assert.Equal(2, c.Cargo.Count); Assert.Equal(10, c.Cargo["water"]); Assert.Equal(5, c.Cargo["food"]); Assert.Equal(2, c.InstalledEquipment.Count); Assert.Equal("eq_engine", c.InstalledEquipment["slot_engine"]); Assert.Equal("eq_shield", c.InstalledEquipment["slot_shield"]); Assert.Equal(2, c.InstalledUpgrades.Count); Assert.Contains("upg_armor", c.InstalledUpgrades); Assert.Contains("upg_speed", c.InstalledUpgrades); Assert.Equal(2, c.Tags.Count); Assert.Contains("military", c.Tags); Assert.Contains("stealth", c.Tags); }
    [Fact] public void Clone_IsIndependent() { var s = CreateValidShip(); s.Cargo["water"] = 10; s.InstalledEquipment["slot_1"] = "eq_original"; s.Tags.Add("original_tag"); var c = s.Clone(); c.Cargo["water"] = 999; c.Cargo["new_item"] = 50; c.InstalledEquipment["slot_1"] = "eq_modified"; c.InstalledEquipment["slot_2"] = "eq_new"; c.Tags.Add("clone_tag"); c.Name = "Modified Clone"; c.CurrentHull = 50; Assert.Equal(10, s.Cargo["water"]); Assert.False(s.Cargo.ContainsKey("new_item")); Assert.Equal("eq_original", s.InstalledEquipment["slot_1"]); Assert.False(s.InstalledEquipment.ContainsKey("slot_2")); Assert.DoesNotContain("clone_tag", s.Tags); Assert.NotEqual("Modified Clone", s.Name); Assert.Equal(200, s.CurrentHull); }
    [Fact] public void Clone_EmptyShip_ClonesCorrectly() { var s = new Ship { Id = "empty_ship", Name = "Empty", ShipClassId = "sc_empty" }; var c = s.Clone(); Assert.Equal("empty_ship", c.Id); Assert.Equal("Empty", c.Name); Assert.Empty(c.Cargo); Assert.Empty(c.InstalledEquipment); Assert.Empty(c.InstalledUpgrades); Assert.Empty(c.Tags); }

    // Serialization
    [Fact] public void Serialize_ProducesValidJson() { var s = CreateValidShip(); s.Cargo["water"] = 10; s.InstalledEquipment["slot_engine"] = "eq_engine"; s.InstalledUpgrades.Add("upg_armor"); s.Tags.Add("military"); var json = s.Serialize(); Assert.Equal("ship_test", json["id"]!.ToString()); Assert.Equal("Test Ship", json["name"]!.ToString()); Assert.Equal("sc_fighter", json["shipClassId"]!.ToString()); Assert.Equal(200, json["currentHull"]!.ToObject<int>()); Assert.Equal(200, json["maxHull"]!.ToObject<int>()); Assert.Equal(100, json["currentShield"]!.ToObject<int>()); Assert.Equal(100, json["maxShield"]!.ToObject<int>()); Assert.Equal(10, json["shieldRechargeRate"]!.ToObject<double>()); Assert.Equal(100, json["cargoCapacity"]!.ToObject<int>()); Assert.Equal(200, json["fuelCapacity"]!.ToObject<int>()); Assert.Equal(200, json["currentFuel"]!.ToObject<int>()); Assert.Equal(1.5, json["fuelConsumption"]!.ToObject<double>()); Assert.Equal(300, json["maxSpeed"]!.ToObject<double>()); Assert.Equal(80, json["acceleration"]!.ToObject<double>()); Assert.Equal(120, json["turnRate"]!.ToObject<double>()); Assert.Equal(3, json["weaponHardpoints"]!.ToObject<int>()); Assert.Equal(2, json["utilityHardpoints"]!.ToObject<int>()); Assert.Equal(4, json["upgradeSlots"]!.ToObject<int>()); Assert.Equal(1.0, json["condition"]!.ToObject<double>()); Assert.Equal(500, json["totalDistanceTraveled"]!.ToObject<double>()); Assert.Equal(100000, json["totalCreditsEarned"]!.ToObject<long>()); Assert.Equal("Neon Station", json["homePort"]!.ToString()); }
    [Fact] public void Deserialize_RestoresAllProperties() { var original = CreateValidShip(); original.Cargo["water"] = 10; original.Cargo["food"] = 5; original.InstalledEquipment["slot_engine"] = "eq_engine"; original.InstalledUpgrades.Add("upg_armor"); original.InstalledUpgrades.Add("upg_speed"); original.Tags.Add("military"); original.Tags.Add("stealth"); var json = original.Serialize(); var restored = new Ship(); restored.Deserialize(json); Assert.Equal(original.Id, restored.Id); Assert.Equal(original.Name, restored.Name); Assert.Equal(original.ShipClassId, restored.ShipClassId); Assert.Equal(original.CurrentHull, restored.CurrentHull); Assert.Equal(original.MaxHull, restored.MaxHull); Assert.Equal(original.CurrentShield, restored.CurrentShield); Assert.Equal(original.MaxShield, restored.MaxShield); Assert.Equal(original.ShieldRechargeRate, restored.ShieldRechargeRate); Assert.Equal(original.CargoCapacity, restored.CargoCapacity); Assert.Equal(original.FuelCapacity, restored.FuelCapacity); Assert.Equal(original.CurrentFuel, restored.CurrentFuel); Assert.Equal(original.FuelConsumption, restored.FuelConsumption); Assert.Equal(original.MaxSpeed, restored.MaxSpeed); Assert.Equal(original.Acceleration, restored.Acceleration); Assert.Equal(original.TurnRate, restored.TurnRate); Assert.Equal(original.WeaponHardpoints, restored.WeaponHardpoints); Assert.Equal(original.UtilityHardpoints, restored.UtilityHardpoints); Assert.Equal(original.UpgradeSlots, restored.UpgradeSlots); Assert.Equal(original.Condition, restored.Condition); Assert.Equal(original.TotalDistanceTraveled, restored.TotalDistanceTraveled); Assert.Equal(original.TotalCreditsEarned, restored.TotalCreditsEarned); Assert.Equal(original.HomePort, restored.HomePort); Assert.Equal(original.PurchaseDate, restored.PurchaseDate); Assert.Equal(2, restored.Cargo.Count); Assert.Equal(10, restored.Cargo["water"]); Assert.Equal(5, restored.Cargo["food"]); Assert.Single(restored.InstalledEquipment); Assert.Equal("eq_engine", restored.InstalledEquipment["slot_engine"]); Assert.Equal(2, restored.InstalledUpgrades.Count); Assert.Contains("upg_armor", restored.InstalledUpgrades); Assert.Contains("upg_speed", restored.InstalledUpgrades); Assert.Equal(2, restored.Tags.Count); Assert.Contains("military", restored.Tags); Assert.Contains("stealth", restored.Tags); }
    [Fact] public void Deserialize_HandlesMissingFields() { var json = new JObject { ["id"] = "ship_minimal", ["name"] = "Minimal", ["shipClassId"] = "sc_min" }; var s = new Ship(); s.Deserialize(json); Assert.Equal("ship_minimal", s.Id); Assert.Equal("Minimal", s.Name); Assert.Equal("sc_min", s.ShipClassId); Assert.Equal(100, s.CurrentHull); Assert.Equal(100, s.MaxHull); Assert.Equal(0, s.CurrentShield); Assert.Equal(50, s.CargoCapacity); Assert.Equal(100, s.FuelCapacity); Assert.Equal(100, s.CurrentFuel); Assert.Equal(1.0, s.FuelConsumption); Assert.Equal(1.0, s.Condition); }
    [Fact] public void SerializeDeserialize_RoundTrip_PreservesData() { var s = CreateValidShip("ship_rt", "Round Trip"); s.Cargo["ore"] = 25; s.Cargo["tech"] = 10; s.InstalledEquipment["slot_w1"] = "wpn_laser"; s.InstalledEquipment["slot_w2"] = "wpn_cannon"; s.InstalledUpgrades.Add("upg_1"); s.InstalledUpgrades.Add("upg_2"); s.InstalledUpgrades.Add("upg_3"); s.Tags.Add("tag_a"); s.Tags.Add("tag_b"); var json = s.Serialize(); var restored = new Ship(); restored.Deserialize(json); Assert.Equal(s.Id, restored.Id); Assert.Equal(s.Name, restored.Name); Assert.Equal(2, restored.Cargo.Count); Assert.Equal(2, restored.InstalledEquipment.Count); Assert.Equal(3, restored.InstalledUpgrades.Count); Assert.Equal(2, restored.Tags.Count); }

    // Registry
    [Fact] public void Registry_Register_AddsShip() { ShipRegistry.Clear(); var s = CreateValidShip("ship_reg", "Registry Ship"); ShipRegistry.Register(s); var r = ShipRegistry.Get("ship_reg"); Assert.NotNull(r); Assert.Equal("Registry Ship", r!.Name); }
    [Fact] public void Registry_Register_InvalidShip_Throws() { ShipRegistry.Clear(); Assert.Throws<ArgumentException>(() => ShipRegistry.Register(new Ship { Id = "", Name = "" })); }
    [Fact] public void Registry_Get_Nonexistent_ReturnsNull() { ShipRegistry.Clear(); Assert.Null(ShipRegistry.Get("nonexistent")); }
    [Fact] public void Registry_All_ReturnsAllRegistered() { ShipRegistry.Clear(); ShipRegistry.Register(CreateValidShip("ship_a", "A")); ShipRegistry.Register(CreateValidShip("ship_b", "B")); Assert.Equal(2, ShipRegistry.All.Count); }
    [Fact] public void Registry_Unregister_RemovesShip() { ShipRegistry.Clear(); var s = CreateValidShip("ship_unreg", "Unregister"); ShipRegistry.Register(s); Assert.NotNull(ShipRegistry.Get("ship_unreg")); Assert.True(ShipRegistry.Unregister("ship_unreg")); Assert.Null(ShipRegistry.Get("ship_unreg")); }
    [Fact] public void Registry_Unregister_Nonexistent_ReturnsFalse() { ShipRegistry.Clear(); Assert.False(ShipRegistry.Unregister("nonexistent")); }
    [Fact] public void Registry_Clear_RemovesAll() { ShipRegistry.Clear(); ShipRegistry.Register(CreateValidShip("ship_1", "One")); ShipRegistry.Register(CreateValidShip("ship_2", "Two")); Assert.Equal(2, ShipRegistry.All.Count); ShipRegistry.Clear(); Assert.Empty(ShipRegistry.All); }

    // GetShipClass
    [Fact] public void GetShipClass_RegisteredClass_ReturnsClass() { ShipClassRegistry.Clear(); var sc = new ShipClass { Id = "sc_fighter", Name = "Fighter", BaseHullIntegrity = 200, BaseFuelCapacity = 150, BaseFuelConsumption = 1.5, BaseMaxSpeed = 300 }; ShipClassRegistry.Register(sc); var s = CreateValidShip(); s.ShipClassId = "sc_fighter"; var r = s.GetShipClass(); Assert.NotNull(r); Assert.Equal("Fighter", r!.Name); }
    [Fact] public void GetShipClass_UnregisteredClass_ReturnsNull() { ShipClassRegistry.Clear(); var s = CreateValidShip(); s.ShipClassId = "nonexistent"; Assert.Null(s.GetShipClass()); }

    // ISaveable
    [Fact] public void SaveId_IsCorrectlyFormatted() { var s = CreateValidShip("ship_save", "Save Test"); Assert.Equal("ship_ship_save", s.SaveId); }
    [Fact] public void SaveVersion_IsOne() { Assert.Equal(1, new Ship().SaveVersion); }

    // Defaults
    [Fact] public void DefaultValues_AreSensible() { var s = new Ship(); Assert.Equal(string.Empty, s.Id); Assert.Equal(string.Empty, s.Name); Assert.Equal(string.Empty, s.ShipClassId); Assert.Equal(100, s.CurrentHull); Assert.Equal(100, s.MaxHull); Assert.Equal(0, s.CurrentShield); Assert.Equal(0, s.MaxShield); Assert.Equal(0, s.ShieldRechargeRate); Assert.Equal(50, s.CargoCapacity); Assert.Equal(100, s.FuelCapacity); Assert.Equal(100, s.CurrentFuel); Assert.Equal(1.0, s.FuelConsumption); Assert.Equal(100, s.MaxSpeed); Assert.Equal(50, s.Acceleration); Assert.Equal(90, s.TurnRate); Assert.Equal(2, s.WeaponHardpoints); Assert.Equal(1, s.UtilityHardpoints); Assert.Equal(3, s.UpgradeSlots); Assert.Equal(1.0, s.Condition); Assert.Equal(0, s.TotalDistanceTraveled); Assert.Equal(0, s.TotalCreditsEarned); Assert.Equal(string.Empty, s.HomePort); Assert.Empty(s.InstalledEquipment); Assert.Empty(s.InstalledUpgrades); Assert.Empty(s.Cargo); Assert.Empty(s.Tags); }

    // Edge Cases
    [Fact] public void TakeDamage_DestroyedShip_NoFurtherEffect() { var s = CreateValidShip(); s.CurrentHull = 0; s.Condition = 0; s.TakeDamage(100); Assert.Equal(0, s.CurrentHull); Assert.Equal(0, s.Condition); }
    [Fact] public void RepairHull_DestroyedShip_CanRepair() { var s = CreateValidShip(); s.CurrentHull = 0; s.MaxHull = 200; s.Condition = 0; var r = s.RepairHull(50); Assert.Equal(50, r); Assert.Equal(50, s.CurrentHull); Assert.Equal(0.25, s.Condition); Assert.False(s.IsDestroyed); }
    [Fact] public void Cargo_MultipleCommodities_TracksCorrectly() { var s = CreateValidShip(); s.CargoCapacity = 500; s.AddCargo("water", 100); s.AddCargo("food", 50); s.AddCargo("ore", 200); s.AddCargo("electronics", 30); Assert.Equal(380, s.GetCargoUsed()); Assert.Equal(120, s.GetAvailableCargoSpace()); }
    [Fact] public void Equipment_InstallRemoveCycle() { var s = CreateValidShip(); Assert.True(s.InstallEquipment("slot_1", "eq_a")); Assert.True(s.HasEquipmentInSlot("slot_1")); Assert.True(s.RemoveEquipment("slot_1", out var r)); Assert.Equal("eq_a", r); Assert.False(s.HasEquipmentInSlot("slot_1")); Assert.True(s.InstallEquipment("slot_1", "eq_b")); Assert.Equal("eq_b", s.GetEquipmentInSlot("slot_1")); }
    [Fact] public void Validate_AllEdgeCases_Valid() { var s = CreateValidShip(); s.CurrentHull = 0; s.CurrentShield = 0; s.MaxShield = 0; s.CargoCapacity = 0; s.Condition = 0; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_CurrentHullEqualsMax_Valid() { var s = CreateValidShip(); s.CurrentHull = 200; s.MaxHull = 200; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_CurrentShieldEqualsMax_Valid() { var s = CreateValidShip(); s.CurrentShield = 100; s.MaxShield = 100; Assert.True(s.Validate(out _)); }
    [Fact] public void Validate_CurrentFuelEqualsCapacity_Valid() { var s = CreateValidShip(); s.CurrentFuel = 200; s.FuelCapacity = 200; Assert.True(s.Validate(out _)); }
    [Fact] public void ConsumeFuel_ThenRefuel_RestoresCorrectly() { var s = CreateValidShip(); s.CurrentFuel = 200; s.FuelCapacity = 200; s.ConsumeFuel(80); Assert.Equal(120, s.CurrentFuel); Assert.Equal(50, s.Refuel(50)); Assert.Equal(170, s.CurrentFuel); Assert.Equal(30, s.Refuel(100)); Assert.Equal(200, s.CurrentFuel); }
}
