using NeonTrader.Models;
using Newtonsoft.Json.Linq;
using Xunit;

namespace NeonTrader.Tests.Models;

[Collection("Sequential")]
public class ShipClassTests
{
    private ShipClass CreateValidShipClass(string id = "sc_fighter", string name = "Fighter Mk I")
    {
        return new ShipClass
        {
            Id = id, Name = name, Type = ShipClassType.Fighter, Size = ShipSize.Small,
            Description = "A nimble fighter", Manufacturer = "Core Dynamics", BaseHullIntegrity = 200,
            BaseShieldCapacity = 50, BaseShieldRecharge = 5.0, BaseCargoCapacity = 20, BaseFuelCapacity = 150,
            BaseFuelConsumption = 1.5, BaseMaxSpeed = 300, BaseAcceleration = 80, BaseTurnRate = 120,
            HardpointCount = 3, UtilityHardpointCount = 1, UpgradeSlotCount = 4, BasePrice = 75000,
            RequiredReputationTier = 1, RequiredFaction = "Federation", IsPlayerPurchasable = true
        };
    }

    [Fact] public void Validate_ValidShipClass_ReturnsTrue() { var sc = CreateValidShipClass(); Assert.True(sc.Validate(out var e)); Assert.Empty(e); }
    [Fact] public void Validate_EmptyId_ReturnsFalse() { var sc = CreateValidShipClass(); sc.Id = ""; Assert.False(sc.Validate(out var e)); Assert.Contains("ID", e); }
    [Fact] public void Validate_WhitespaceId_ReturnsFalse() { var sc = CreateValidShipClass(); sc.Id = "   "; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_EmptyName_ReturnsFalse() { var sc = CreateValidShipClass(); sc.Name = ""; Assert.False(sc.Validate(out var e)); Assert.Contains("name", e); }
    [Fact] public void Validate_ZeroHullIntegrity_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseHullIntegrity = 0; Assert.False(sc.Validate(out var e)); Assert.Contains("hull", e); }
    [Fact] public void Validate_NegativeHullIntegrity_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseHullIntegrity = -10; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_NegativeCargoCapacity_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseCargoCapacity = -1; Assert.False(sc.Validate(out var e)); Assert.Contains("cargo", e); }
    [Fact] public void Validate_ZeroFuelCapacity_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseFuelCapacity = 0; Assert.False(sc.Validate(out var e)); Assert.Contains("fuel", e); }
    [Fact] public void Validate_ZeroFuelConsumption_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseFuelConsumption = 0; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_ZeroMaxSpeed_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BaseMaxSpeed = 0; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_NegativeHardpointCount_ReturnsFalse() { var sc = CreateValidShipClass(); sc.HardpointCount = -1; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_NegativeUtilityHardpointCount_ReturnsFalse() { var sc = CreateValidShipClass(); sc.UtilityHardpointCount = -1; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_NegativeUpgradeSlotCount_ReturnsFalse() { var sc = CreateValidShipClass(); sc.UpgradeSlotCount = -1; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_NegativeBasePrice_ReturnsFalse() { var sc = CreateValidShipClass(); sc.BasePrice = -100; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_ReputationTierTooHigh_ReturnsFalse() { var sc = CreateValidShipClass(); sc.RequiredReputationTier = 5; Assert.False(sc.Validate(out var e)); Assert.Contains("reputation", e); }
    [Fact] public void Validate_ReputationTierNegative_ReturnsFalse() { var sc = CreateValidShipClass(); sc.RequiredReputationTier = -1; Assert.False(sc.Validate(out var e)); }
    [Fact] public void Validate_ZeroHardpoints_Valid() { var sc = CreateValidShipClass(); sc.HardpointCount = 0; sc.UtilityHardpointCount = 0; sc.UpgradeSlotCount = 0; Assert.True(sc.Validate(out _)); }

    [Fact] public void DefaultValues_AreSensible() { var sc = new ShipClass(); Assert.Equal(string.Empty, sc.Id); Assert.Equal(string.Empty, sc.Name); Assert.Equal(ShipClassType.Freighter, sc.Type); Assert.Equal(ShipSize.Medium, sc.Size); Assert.Equal(100, sc.BaseHullIntegrity); Assert.Equal(0, sc.BaseShieldCapacity); Assert.Equal(0, sc.BaseShieldRecharge); Assert.Equal(50, sc.BaseCargoCapacity); Assert.Equal(100, sc.BaseFuelCapacity); Assert.Equal(1.0, sc.BaseFuelConsumption); Assert.Equal(100, sc.BaseMaxSpeed); Assert.Equal(50, sc.BaseAcceleration); Assert.Equal(90, sc.BaseTurnRate); Assert.Equal(2, sc.HardpointCount); Assert.Equal(1, sc.UtilityHardpointCount); Assert.Equal(3, sc.UpgradeSlotCount); Assert.Equal(50000, sc.BasePrice); Assert.Equal(0, sc.RequiredReputationTier); Assert.Equal(string.Empty, sc.RequiredFaction); Assert.True(sc.IsPlayerPurchasable); Assert.Empty(sc.Tags); Assert.Empty(sc.StatMultipliers); Assert.Empty(sc.DefaultEquipment); }

    [Fact] public void Clone_CreatesDeepCopy() { var sc = CreateValidShipClass(); sc.Tags.Add("stealth"); sc.Tags.Add("military"); sc.StatMultipliers["cargo"] = 1.5; sc.StatMultipliers["speed"] = 1.2; sc.DefaultEquipment.Add("eq_laser"); sc.DefaultEquipment.Add("eq_shield_gen"); var clone = sc.Clone(); Assert.Equal(sc.Id, clone.Id); Assert.Equal(sc.Name, clone.Name); Assert.Equal(sc.Type, clone.Type); Assert.Equal(sc.Size, clone.Size); Assert.Equal(sc.Description, clone.Description); Assert.Equal(sc.Manufacturer, clone.Manufacturer); Assert.Equal(sc.BaseHullIntegrity, clone.BaseHullIntegrity); Assert.Equal(sc.BaseShieldCapacity, clone.BaseShieldCapacity); Assert.Equal(sc.BaseShieldRecharge, clone.BaseShieldRecharge); Assert.Equal(sc.BaseCargoCapacity, clone.BaseCargoCapacity); Assert.Equal(sc.BaseFuelCapacity, clone.BaseFuelCapacity); Assert.Equal(sc.BaseFuelConsumption, clone.BaseFuelConsumption); Assert.Equal(sc.BaseMaxSpeed, clone.BaseMaxSpeed); Assert.Equal(sc.BaseAcceleration, clone.BaseAcceleration); Assert.Equal(sc.BaseTurnRate, clone.BaseTurnRate); Assert.Equal(sc.HardpointCount, clone.HardpointCount); Assert.Equal(sc.UtilityHardpointCount, clone.UtilityHardpointCount); Assert.Equal(sc.UpgradeSlotCount, clone.UpgradeSlotCount); Assert.Equal(sc.BasePrice, clone.BasePrice); Assert.Equal(sc.RequiredReputationTier, clone.RequiredReputationTier); Assert.Equal(sc.RequiredFaction, clone.RequiredFaction); Assert.Equal(sc.IsPlayerPurchasable, clone.IsPlayerPurchasable); Assert.Equal(2, clone.Tags.Count); Assert.Contains("stealth", clone.Tags); Assert.Contains("military", clone.Tags); Assert.Equal(2, clone.StatMultipliers.Count); Assert.Equal(1.5, clone.StatMultipliers["cargo"]); Assert.Equal(1.2, clone.StatMultipliers["speed"]); Assert.Equal(2, clone.DefaultEquipment.Count); Assert.Contains("eq_laser", clone.DefaultEquipment); Assert.Contains("eq_shield_gen", clone.DefaultEquipment); }
    [Fact] public void Clone_IsIndependent() { var sc = CreateValidShipClass(); sc.Tags.Add("original"); var clone = sc.Clone(); clone.Tags.Add("clone_only"); clone.Name = "Modified Clone"; Assert.Contains("original", sc.Tags); Assert.DoesNotContain("clone_only", sc.Tags); Assert.NotEqual(clone.Name, sc.Name); }

    [Fact] public void Serialize_ProducesValidJson() { var sc = CreateValidShipClass(); sc.Tags.Add("stealth"); sc.StatMultipliers["cargo"] = 1.5; sc.DefaultEquipment.Add("eq_laser"); var json = sc.Serialize(); Assert.Equal("sc_fighter", json["id"]!.ToString()); Assert.Equal("Fighter Mk I", json["name"]!.ToString()); Assert.Equal("Fighter", json["type"]!.ToString()); Assert.Equal("Small", json["size"]!.ToString()); Assert.Equal(200, json["baseHullIntegrity"]!.ToObject<int>()); Assert.Equal(50, json["baseShieldCapacity"]!.ToObject<int>()); Assert.Equal(5.0, json["baseShieldRecharge"]!.ToObject<double>()); Assert.Equal(20, json["baseCargoCapacity"]!.ToObject<int>()); Assert.Equal(150, json["baseFuelCapacity"]!.ToObject<int>()); Assert.Equal(1.5, json["baseFuelConsumption"]!.ToObject<double>()); Assert.Equal(300, json["baseMaxSpeed"]!.ToObject<double>()); Assert.Equal(80, json["baseAcceleration"]!.ToObject<double>()); Assert.Equal(120, json["baseTurnRate"]!.ToObject<double>()); Assert.Equal(3, json["hardpointCount"]!.ToObject<int>()); Assert.Equal(1, json["utilityHardpointCount"]!.ToObject<int>()); Assert.Equal(4, json["upgradeSlotCount"]!.ToObject<int>()); Assert.Equal(75000, json["basePrice"]!.ToObject<long>()); Assert.Equal(1, json["requiredReputationTier"]!.ToObject<int>()); Assert.Equal("Federation", json["requiredFaction"]!.ToString()); }
    [Fact] public void Deserialize_RestoresAllProperties() { var original = CreateValidShipClass(); original.Tags.Add("stealth"); original.StatMultipliers["cargo"] = 1.5; original.DefaultEquipment.Add("eq_laser"); var json = original.Serialize(); var restored = new ShipClass(); restored.Deserialize(json); Assert.Equal(original.Id, restored.Id); Assert.Equal(original.Name, restored.Name); Assert.Equal(original.Type, restored.Type); Assert.Equal(original.Size, restored.Size); Assert.Equal(original.Description, restored.Description); Assert.Equal(original.Manufacturer, restored.Manufacturer); Assert.Equal(original.BaseHullIntegrity, restored.BaseHullIntegrity); Assert.Equal(original.BaseShieldCapacity, restored.BaseShieldCapacity); Assert.Equal(original.BaseShieldRecharge, restored.BaseShieldRecharge); Assert.Equal(original.BaseCargoCapacity, restored.BaseCargoCapacity); Assert.Equal(original.BaseFuelCapacity, restored.BaseFuelCapacity); Assert.Equal(original.BaseFuelConsumption, restored.BaseFuelConsumption); Assert.Equal(original.BaseMaxSpeed, restored.BaseMaxSpeed); Assert.Equal(original.BaseAcceleration, restored.BaseAcceleration); Assert.Equal(original.BaseTurnRate, restored.BaseTurnRate); Assert.Equal(original.HardpointCount, restored.HardpointCount); Assert.Equal(original.UtilityHardpointCount, restored.UtilityHardpointCount); Assert.Equal(original.UpgradeSlotCount, restored.UpgradeSlotCount); Assert.Equal(original.BasePrice, restored.BasePrice); Assert.Equal(original.RequiredReputationTier, restored.RequiredReputationTier); Assert.Equal(original.RequiredFaction, restored.RequiredFaction); Assert.Contains("stealth", restored.Tags); Assert.Equal(1.5, restored.StatMultipliers["cargo"]); Assert.Contains("eq_laser", restored.DefaultEquipment); }
    [Fact] public void Deserialize_HandlesMissingFields() { var json = new JObject { ["id"] = "sc_minimal", ["name"] = "Minimal" }; var sc = new ShipClass(); sc.Deserialize(json); Assert.Equal("sc_minimal", sc.Id); Assert.Equal("Minimal", sc.Name); Assert.Equal(100, sc.BaseHullIntegrity); Assert.Equal(0, sc.BaseShieldCapacity); Assert.Equal(50, sc.BaseCargoCapacity); }
    [Fact] public void SerializeDeserialize_RoundTrip_PreservesData() { var sc = CreateValidShipClass("sc_roundtrip", "Round Trip"); sc.Tags.Add("tag1"); sc.Tags.Add("tag2"); sc.StatMultipliers["speed"] = 1.3; sc.StatMultipliers["armor"] = 1.1; sc.DefaultEquipment.Add("eq_a"); sc.DefaultEquipment.Add("eq_b"); var json = sc.Serialize(); var restored = new ShipClass(); restored.Deserialize(json); Assert.Equal(sc.Id, restored.Id); Assert.Equal(sc.Name, restored.Name); Assert.Equal(sc.Type, restored.Type); Assert.Equal(sc.Size, restored.Size); Assert.Equal(2, restored.Tags.Count); Assert.Equal(2, restored.StatMultipliers.Count); Assert.Equal(2, restored.DefaultEquipment.Count); }

    [Fact] public void Registry_Register_AddsShipClass() { ShipClassRegistry.Clear(); var sc = CreateValidShipClass("sc_reg_test", "Registry Test"); ShipClassRegistry.Register(sc); var r = ShipClassRegistry.Get("sc_reg_test"); Assert.NotNull(r); Assert.Equal("Registry Test", r!.Name); }
    [Fact] public void Registry_Register_InvalidShipClass_Throws() { ShipClassRegistry.Clear(); Assert.Throws<ArgumentException>(() => ShipClassRegistry.Register(new ShipClass { Id = "", Name = "" })); }
    [Fact] public void Registry_Get_Nonexistent_ReturnsNull() { ShipClassRegistry.Clear(); Assert.Null(ShipClassRegistry.Get("nonexistent")); }
    [Fact] public void Registry_All_ReturnsAllRegistered() { ShipClassRegistry.Clear(); ShipClassRegistry.Register(CreateValidShipClass("sc_a", "A")); ShipClassRegistry.Register(CreateValidShipClass("sc_b", "B")); Assert.Equal(2, ShipClassRegistry.All.Count); }
    [Fact] public void Registry_GetByType_FiltersCorrectly() { ShipClassRegistry.Clear(); var f1 = CreateValidShipClass("sc_f1", "Fighter 1"); f1.Type = ShipClassType.Fighter; var fr1 = CreateValidShipClass("sc_fr1", "Freighter 1"); fr1.Type = ShipClassType.Freighter; var f2 = CreateValidShipClass("sc_f2", "Fighter 2"); f2.Type = ShipClassType.Fighter; ShipClassRegistry.Register(f1); ShipClassRegistry.Register(fr1); ShipClassRegistry.Register(f2); Assert.Equal(2, ShipClassRegistry.GetByType(ShipClassType.Fighter).Count); Assert.Single(ShipClassRegistry.GetByType(ShipClassType.Freighter)); }
    [Fact] public void Registry_GetBySize_FiltersCorrectly() { ShipClassRegistry.Clear(); var sm = CreateValidShipClass("sc_sm", "Small"); sm.Size = ShipSize.Small; var md = CreateValidShipClass("sc_md", "Medium"); md.Size = ShipSize.Medium; ShipClassRegistry.Register(sm); ShipClassRegistry.Register(md); Assert.Single(ShipClassRegistry.GetBySize(ShipSize.Small)); Assert.Empty(ShipClassRegistry.GetBySize(ShipSize.Large)); }
    [Fact] public void Registry_Clear_RemovesAll() { ShipClassRegistry.Clear(); ShipClassRegistry.Register(CreateValidShipClass("sc_1", "One")); ShipClassRegistry.Register(CreateValidShipClass("sc_2", "Two")); Assert.Equal(2, ShipClassRegistry.All.Count); ShipClassRegistry.Clear(); Assert.Empty(ShipClassRegistry.All); }
    [Fact] public void Registry_LoadFromJson_PopulatesRegistry() { ShipClassRegistry.Clear(); var json = @"[ { ""id"": ""sc_json_a"", ""name"": ""JSON A"", ""type"": ""Fighter"", ""size"": ""Small"", ""baseHullIntegrity"": 150, ""baseFuelCapacity"": 120, ""baseFuelConsumption"": 1.2, ""baseMaxSpeed"": 250, ""basePrice"": 60000 }, { ""id"": ""sc_json_b"", ""name"": ""JSON B"", ""type"": ""Freighter"", ""size"": ""Large"", ""baseHullIntegrity"": 500, ""baseFuelCapacity"": 400, ""baseFuelConsumption"": 2.0, ""baseMaxSpeed"": 80, ""basePrice"": 200000 } ]"; ShipClassRegistry.LoadFromJson(json); Assert.Equal(2, ShipClassRegistry.All.Count); var a = ShipClassRegistry.Get("sc_json_a"); Assert.NotNull(a); Assert.Equal("JSON A", a!.Name); Assert.Equal(ShipClassType.Fighter, a.Type); Assert.Equal(150, a.BaseHullIntegrity); var b = ShipClassRegistry.Get("sc_json_b"); Assert.NotNull(b); Assert.Equal("JSON B", b!.Name); Assert.Equal(ShipClassType.Freighter, b.Type); Assert.Equal(500, b.BaseHullIntegrity); }

    [Fact] public void SaveId_IsCorrectlyFormatted() { var sc = CreateValidShipClass("sc_save", "Save Test"); Assert.Equal("shipclass_sc_save", sc.SaveId); }
    [Fact] public void SaveVersion_IsOne() { Assert.Equal(1, new ShipClass().SaveVersion); }

    [Fact] public void ShipClassType_AllValues_CanBeSet() { foreach (ShipClassType t in Enum.GetValues<ShipClassType>()) { var sc = CreateValidShipClass(); sc.Type = t; Assert.Equal(t, sc.Type); } }
    [Fact] public void ShipSize_AllValues_CanBeSet() { foreach (ShipSize s in Enum.GetValues<ShipSize>()) { var sc = CreateValidShipClass(); sc.Size = s; Assert.Equal(s, sc.Size); } }

    [Fact] public void Validate_ZeroCargoCapacity_Valid() { var sc = CreateValidShipClass(); sc.BaseCargoCapacity = 0; Assert.True(sc.Validate(out _)); }
    [Fact] public void Validate_ZeroShieldCapacity_Valid() { var sc = CreateValidShipClass(); sc.BaseShieldCapacity = 0; sc.BaseShieldRecharge = 0; Assert.True(sc.Validate(out _)); }
    [Fact] public void Validate_ReputationTierZero_Valid() { var sc = CreateValidShipClass(); sc.RequiredReputationTier = 0; Assert.True(sc.Validate(out _)); }
    [Fact] public void Validate_ReputationTierFour_Valid() { var sc = CreateValidShipClass(); sc.RequiredReputationTier = 4; Assert.True(sc.Validate(out _)); }
    [Fact] public void Validate_EmptyRequiredFaction_Valid() { var sc = CreateValidShipClass(); sc.RequiredFaction = ""; Assert.True(sc.Validate(out _)); }
    [Fact] public void Validate_NotPlayerPurchasable_Valid() { var sc = CreateValidShipClass(); sc.IsPlayerPurchasable = false; Assert.True(sc.Validate(out _)); }
}
